name: Release wheels

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Version bump (+1=major, +0.1=minor, +0.0.1=patch)"
        required: true
        default: "+0.0.1"
        type: choice
        options: ["+1", "+0.1", "+0.0.1"]

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump
        run: |
          new_version=$(python .github/scripts/bump_version.py ${{ inputs.increment }})
          echo "version=$new_version" >> "$GITHUB_OUTPUT"
      - name: Commit version and tag
        id: commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "Bump version to ${{ steps.bump.outputs.version }}"
          git tag "v${{ steps.bump.outputs.version }}"
          git push origin HEAD --tags
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  build:
    name: Build wheels on ${{ matrix.os }}
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-13", "macos-14"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Upgrade build toolchain
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel
      - name: Clean
        shell: bash
        run: |
          python -c "import shutil,glob;[shutil.rmtree(p,ignore_errors=True) for p in ('wheelhouse','build','dist')]; \
                     [shutil.rmtree(e,ignore_errors=True) for e in glob.glob('*.egg-info')]"
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64 x86"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel}"
      - name: Validate wheel ZIP structure
        shell: bash
        run: |
          python -c "import glob,zipfile,sys; ws=sorted(glob.glob('wheelhouse/*.whl')); \
                     sys.exit('No wheels found') if not ws else None; \
                     [(_ for _ in ()).throw(SystemExit(f'Corrupt entry in {w}')) \
                     if (lambda z: z.testzip())(zipfile.ZipFile(w)) else None \
                     for w in ws]"
      - name: Hash wheels (cross-platform)
        shell: bash
        run: |
          python -c "import hashlib,glob,pathlib,os; out=pathlib.Path('wheelhouse')/f'SHA256SUMS-{os.environ.get('RUNNER_OS','unknown')}'; \
                     fh=open(out,'w'); \
                     [fh.write(f\"{hashlib.sha256(open(p,'rb').read()).hexdigest()}  {pathlib.Path(p).name}\\n\") \
                     for p in sorted(glob.glob('wheelhouse/*.whl'))]; fh.close(); print('Wrote',out)"
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: |
            wheelhouse/*.whl
            wheelhouse/SHA256SUMS-*
          if-no-files-found: error
          compression-level: 0

  publish:
    name: Publish to PyPI (Linux only)
    needs: [build, prepare]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Verify ZIP integrity
        shell: bash
        run: |
          python -c "import glob,zipfile,sys; ws=sorted(glob.glob('wheelhouse/*.whl')); \
                     sys.exit('No wheels found') if not ws else None; \
                     [(_ for _ in ()).throw(SystemExit(f'Corrupt entry in {w}')) \
                     if (lambda z: z.testzip())(zipfile.ZipFile(w)) else None \
                     for w in ws]; print(f'Verified {len(ws)} wheels')"
      - name: Verify checksums (cross-platform)
        shell: bash
        run: |
          python -c "import hashlib,glob,pathlib; exp=sorted(open('wheelhouse/SHA256SUMS-linux-gnu','a+').read().splitlines()+ \
                     sum([open(p).read().splitlines() for p in sorted(glob.glob('wheelhouse/SHA256SUMS-*'))], [])); \
                     act=sorted([f\"{hashlib.sha256(open(p,'rb').read()).hexdigest()}  {pathlib.Path(p).name}\" \
                     for p in sorted(glob.glob('wheelhouse/*.whl'))]); \
                     import sys; sys.exit('Checksum mismatch') if exp!=act else print('Checksums OK')"
      - name: Twine metadata check
        run: |
          python -m pip install -U twine pkginfo
          twine check wheelhouse/*.whl
      - name: Upload to PyPI (trusted publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse

  github-release:
    name: Create GitHub Release
    needs: [publish, prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true
      - name: Generate combined checksums
        shell: bash
        run: |
          python -c "import hashlib,glob,pathlib; out=pathlib.Path('wheelhouse')/'SHA256SUMS'; \
                     fh=open(out,'w'); \
                     [fh.write(f\"{hashlib.sha256(open(p,'rb').read()).hexdigest()}  {pathlib.Path(p).name}\\n\") \
                     for p in sorted(glob.glob('wheelhouse/*.whl'))]; fh.close(); print('Wrote',out)"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          name: v${{ needs.prepare.outputs.version }}
          files: |
            wheelhouse/*.whl
            wheelhouse/SHA256SUMS
