name: Release wheels

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version bump (+1=major, +0.1=minor, +0.0.1=patch)'
        required: true
        default: '+0.0.1'
        type: choice
        options:
          - '+1'
          - '+0.1'
          - '+0.0.1'

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump
        run: |
          new_version=$(python .github/scripts/bump_version.py ${{ inputs.increment }})
          echo "version=$new_version" >> "$GITHUB_OUTPUT"
      - name: Commit version
        id: commit
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "Bump version to ${{ steps.bump.outputs.version }}"
          git tag "v${{ steps.bump.outputs.version }}"
          git push origin HEAD --tags
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  build:
    name: Build wheels on ${{ matrix.os }}
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel twine
      - name: Clean
        run: rm -rf wheelhouse build dist *.egg-info
        shell: bash
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64 x86"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel}"
      - name: Validate wheel ZIP structure
        run: python -m zipfile -t wheelhouse/*.whl
      - name: Twine metadata check
        run: twine check wheelhouse/*
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error
          compression-level: 0

  publish:
    runs-on: ubuntu-latest
    needs: [build, prepare]
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Verify integrity after download
        run: python -m zipfile -t wheelhouse/*.whl
      - name: Generate checksums
        run: |
          cd wheelhouse
          sha256sum *.whl > SHA256SUMS
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          name: v${{ needs.prepare.outputs.version }}
          files: |
            wheelhouse/*.whl
            wheelhouse/SHA256SUMS
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
